---

  - file: path=/opt/maxhurl-site state=absent

  - git: repo=https://github.com/maximilianhurl/maxhurl-site.git dest=/opt/maxhurl-site


  - name: copy secrets
    sudo: true
    copy: src=../../../../../secrets.py dest=/opt/maxhurl-site/


  - name: copy supervisord config
    sudo: true
    copy: src=../../../../../etc/supervisord/ dest=/opt/maxhurl-site/etc/supervisord/


  - name: start supervisord
    command: supervisord -c /opt/maxhurl-site/etc/supervisord/supervisord.conf
    ignore_errors: yes


  - name: install requirements
    pip: requirements=/opt/maxhurl-site/requirements.txt virtualenv=/opt/maxhurl-site/env


  - name: start supervisorctl
    supervisorctl: name=maxhurl_flask state=restarted config=/opt/maxhurl-site/etc/supervisord/supervisord.conf
    notify: restart nginx

