---

  - name: copy static files
    sudo: true
    copy: src=../../../../../static dest=/opt/maxhurl-site/


  - name: copy template files
    sudo: true
    copy: src=../../../../../templates dest=/opt/maxhurl-site/


  - name: copy requirements
    sudo: true
    copy: src=../../../../../requirements.txt dest=/opt/maxhurl-site/


  - name: copy flask app
    sudo: true
    copy: src=../../../../../maxhurl.py dest=/opt/maxhurl-site/


  - name: copy secrets
    sudo: true
    copy: src=../../../../../secrets.py dest=/opt/maxhurl-site/


  - name: copy supervisord config
    sudo: true
    copy: src=../../../../../etc/supervisord/ dest=/opt/maxhurl-site/etc/supervisord/


  - name: start supervisord
    command: supervisord -c /opt/maxhurl-site/etc/supervisord/supervisord.conf
    ignore_errors: yes


  - name: install requirements
    pip: requirements=/opt/maxhurl-site/requirements.txt virtualenv=/opt/maxhurl-site/env


  - name: start supervisorctl
    supervisorctl: name=maxhurl_flask state=restarted config=/opt/maxhurl-site/etc/supervisord/supervisord.conf
    notify: restart nginx


  # - name: reread supervisorctl
  #   shell: supervisorctl -c /opt/maxhurl-site/etc/supervisord/supervisord.conf reread


  # - name: update supervisorctl
  #   shell: supervisorctl -c /opt/maxhurl-site/etc/supervisord/supervisord.conf update


  #- name: start/restart flask app
  #  supervisorctl: name=maxhurl_flask state=restarted config=/opt/maxhurl-site/supervisord/supervisord.conf
  #  notify: restart nginx
