---

  - name: apt get update
    sudo: true
    apt: update_cache=yes


  - name: install pip
    sudo: true
    apt: name=python-pip state=present


  - name: install nginx server
    sudo: true
    apt: name=nginx state=present


  - name: upgrade pip
    sudo: true
    pip: name=pip state=present extra_args="--upgrade"


  - name: upgrade setuptools
    sudo: true
    pip: name=setuptools state=present extra_args="--upgrade"


  - name: install virtualenv
    sudo: true
    pip: name=virtualenv state=present


  - name: install supervisord
    sudo: true
    pip: name=supervisor state=present


  - name: copy nginx virtualhost sites-available config
    sudo: true
    copy: src=maxhurl.co.uk dest=/etc/nginx/sites-available/maxhurl.co.uk

  - name: remove default nginx config
    sudo: true
    command: rm /etc/nginx/sites-enabled/default
    ignore_errors: yes

  - name: copy nginx virtualhost sites-enabled config
    sudo: true
    copy: src=maxhurl.co.uk dest=/etc/nginx/sites-enabled/maxhurl.co.uk
    notify: restart nginx
