name: Pull Request
env:
  NODE_VERSION: '18.12'
on:
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set node version to ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install Deps
        run: |
          npm ci

      - name: Build
        run: npm run build

      - name: Prettier
        run: npm run check

      - name: Lint
        run: npm run lint
